name: slicing
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  accordion: ^2.6.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  gap: ^3.0.1
  get: ^4.6.6
  google_fonts: ^4.0.4
  lint: ^2.3.0
  loading_animation_widget: ^1.2.1
  smooth_page_indicator: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/guideProfile.png"
  min_sdk_android:
  web:
    generate: true
    image_path: "assets/images/guideProfile.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/images/guideProfile.png"

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
